name = "stormberry-contact-form"
main = "index.js"
compatibility_date = "2024-03-20"

# [vars]
# ADMIN_EMAIL = "admin@stormberry.no" # Change this to the inbox where inquiries should go
# SENDER_EMAIL = "no-reply@stormberry.as" # Change this to a verified sender on your domain

# [[send_email]]
# name = "SEB"
# destination_address = "admin@stormberry.no" # Same as ADMIN_EMAIL above (optional restriction)
